name: Call Reusable Postman Workflow

on:
  workflow_dispatch: # Allows manual triggering
    inputs:
      collection_name:
        description: 'Name for the Postman collection'
        required: true
        default: 'My Test API Collection from Caller'
      openapi_file:
        description: 'Path to the OpenAPI spec file'
        required: true
        default: 'cloudformation/openapi.yaml'
      folder_structure:
        description: 'Optional folder structure in Postman (e.g., Team/Project)'
        required: false
        default: 'CallerTeam/CallerProject'

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/reusable_manage_postman_collection.yaml
    with:
      collection_name: ${{ github.event.inputs.collection_name }}
      openapi_file_path: ${{ github.event.inputs.openapi_file }}
      folder_structure: ${{ github.event.inputs.folder_structure }}
    secrets:
      postman_api_key: ${{ secrets.POSTMAN_API_KEY }} # Ensure this secret is set in your repository
      postman_workspace_id: ${{ secrets.POSTMAN_WORKSPACE_ID }} # Ensure this secret is set in your repository

  report_outputs:
    runs-on: ubuntu-latest
    needs: call_reusable_workflow
    if: always() # Run this job even if the reusable workflow fails, to see partial outputs or errors
    steps:
      - name: Display Reusable Workflow Outputs
        run: |
          echo "Reusable workflow execution completed."
          echo "Collection UID: ${{ needs.call_reusable_workflow.outputs.collection_uid }}"
          echo "Collection URL: ${{ needs.call_reusable_workflow.outputs.collection_url }}"
          
          if [ -z "${{ needs.call_reusable_workflow.outputs.collection_uid }}" ]; then
            echo "Warning: Collection UID is empty. The reusable workflow might have failed or did not produce a UID."
          fi
